# Generated by Django 4.1.1 on 2022-10-07 14:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matchs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="match_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(blank=True, null=True),
                null=True,
                size=None,
            ),
        ),
    ]
