# Generated by Django 4.1.1 on 2022-10-10 10:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matchs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="match_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), size=None
                    ),
                    size=None,
                ),
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="court_number",
            field=models.IntegerField(default=0),
        ),
    ]
