# Generated by Django 4.1.1 on 2022-10-10 12:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matchs", "0005_alter_match_match_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="match_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10, null=True),
                        null=True,
                        size=None,
                    ),
                    default=list,
                    size=None,
                ),
                default=list,
                size=None,
            ),
        ),
    ]
