# Generated by Django 4.1.1 on 2022-10-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matchs", "0007_alter_match_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="goals_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="match_count",
            field=models.IntegerField(default=0),
        ),
    ]
