# Generated by Django 4.1.1 on 2022-10-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matchs", "0008_member_goals_score_member_match_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="goals_score_rate",
            field=models.IntegerField(default=0),
        ),
    ]
