# Generated by Django 4.1.1 on 2022-10-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matchs", "0009_member_goals_score_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="limit_game_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="win",
            field=models.IntegerField(default=0),
        ),
    ]
