# Generated by Django 4.1.1 on 2022-10-21 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matchs", "0010_match_limit_game_count_member_win"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="limit_game_count",
        ),
    ]
