# Generated by Django 4.1.1 on 2022-10-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matchs", "0011_remove_match_limit_game_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="type",
            field=models.CharField(
                choices=[("1", "同時進行"), ("2", "先取")],
                default="1",
                max_length=15,
                verbose_name="試合の種類",
            ),
        ),
    ]
